#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 */

use yii\console\Application;
use yii\helpers\ArrayHelper;
use yii\base\InvalidConfigException;

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/config/bootstrap.php';

$config = ArrayHelper::merge(
    require __DIR__ . '/config/common.php',
    require __DIR__ . '/config/console.php'
);

try {
    $exitCode = (new Application($config))->run();
} catch (InvalidConfigException $e) {
    if (YII_DEBUG) exit($e->getMessage());
}

exit($exitCode);
